### ISSUE TITLE
Parser is not case insensitive

### ISSUE THREAD

**Issue by guilbaudl** [VHDL-LS/rust_hdl#130] opened 2022-07-04 14:18 UTC
Hello,
 
It seems the parser is sensitive to case when you end the definition of a component. Here is a picture:
![image](https://user-images.githubusercontent.com/57914748/177172957-6b1afb35-8de0-48bf-8e39-decbc25f96b1.png)
I tried the same with entities, package, no problem, but here it is.

**Comment by jeanthom** [comment] 2022-08-13 09:08
Duplicate of #120

**Comment by kraigher** [comment] 2022-12-07 17:17
VHDL LS the language server does not do any syntax highlighting so that function is not part of this project.  Direct you report towards: https://github.com/VHDL-LS/rust_hdl_vscode

**Closed by kraigher** 2022-12-07 17:17 UTC
