### ISSUE TITLE
Re-defined library

### ISSUE THREAD

**Issue by jakobjung10** [VHDL-LS/rust_hdl#252] opened 2024-01-26 14:35 UTC
![redefined_library](https://github.com/VHDL-LS/rust_hdl/assets/116195279/44218fe8-20a2-4bb9-a1eb-8b35d2a9d93b)

Why do we need this warning?

**Comment by Schottkyc137** [comment] 2024-02-04 21:02
When does this warning occur?

**Comment by jakobjung10** [comment] 2024-02-04 21:10
Everytime you make changes to the _vhdl_ls.toml_ in the client (VSCode).

**Comment by Schottkyc137** [comment] 2024-02-05 08:25
Unfortunately I cannot reproduce the warning. Can you give a minimal reproducible example?

**Comment by Schottkyc137** [comment] 2024-09-02 16:03
This is an intended warning occurring when one defines a library twice. As this is expected, I'll close this issue.

**Closed** 2024-09-02 16:03 UTC
